name: Deploy To S3 And Ivalidate Cloudfront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: Repository 파일 출력하기
        run: ls

      - name: 빌드하기
        run: npm run build

      - name: Debugging
        run: |
          ls
          cd dist
          ls
